### ISSUE TITLE
 'S3' object has no attribute '__aenter__'

### ISSUE THREAD

**Issue by dxunix** [dask/s3fs#385]
**What happened**: 
Got an error saying `'S3' object has no attribute '__aenter__'`

**What you expected to happen**:
Should not see this
**Minimal Complete Verifiable Example**:

```python
s3fs.S3FileSystem(
                session=botocore.session.Session(
                    profile=cls.__aws_profile)).open
```

**Anything else we need to know?**:
works fine with 0.4.2
but it does not with 0.5.1
**Environment**:

- Dask version:
- Python version: 3.8
- Operating System: MacOS
- Install method (conda, pip, source):
conda and pip

**Comment by martindurant** [comment]
Since `s3fs` is now based on `aiobotocore`, you must pass a `aiobotocore.AioSession` instance instead - see the [docstring](https://s3fs.readthedocs.io/en/latest/api.html#s3fs.core.S3FileSystem).

**Comment by callumm-graphcore** [comment]
Minor note for fellow future Googlers: the correct class to import seems to be `aiobotocore.session.AioSession`, not `aiobotocore.AioSession`
